### ISSUE TITLE
compas_ifc + grasshopper

### ISSUE THREAD

**Issue by keshavanarayan** [compas-dev/compas_ifc#3]
Hi compas team,

Thank you so much for this amazing library. 
I was wondering if it is possible to make `compas_ifc` work with grasshopper the same way in which the core `compas` library works in gh? 

I tried `import compas_ifc` in ghpython but it says `No module named compas_ifc`. 
Are there any plans to make this work in the future?
In the short term, is there a way to make it work now?
Any suggestion / direction is highly appreciated.

Thank you again for this.

**Comment by Licini** [comment]
Hi @keshavanarayan it will be a bit challenging, since compas_ifc depends on `ifcopenshell` which does not existing in IronPython of Rhino. It is possible to interact with it using `compas.rpc` or `compas_cloud`, could you describe what kind of operations you want to achieve inside gh?

**Comment by keshavanarayan** [comment]
Reading and creating ifc files from gh is the idea.

**Comment by keshavanarayan** [comment]
Rhino updating to python3 has solved this. Thank you.
